import {
  BtnArrowIcon,
  BurgerIcon, closeModalIcon, ComeBackIcon, errorModalIcon,
  formCityIcon,
  formPassIcon,
  formUserIcon, infoModalIcon, InstructionIcon,
  LogoutIcon,
  PastTestIcon,
  RCorrectIcon,
  RulesIcon,
  RWrongIcon, StudentIcon, successModalIcon, testDurationIcon, testPriceIcon, TestsIcon, testTypeIcon,
  UserIcon, VariantDeleteIcon, VariantIcon,
} from "./own";


export default {
  BurgerIcon,
  UserIcon,
  PastTestIcon,
  RulesIcon,
  InstructionIcon,
  LogoutIcon,
  RCorrectIcon,
  RWrongIcon,
  formUserIcon,
  formPassIcon,
  formCityIcon,
  testTypeIcon,
  testDurationIcon,
  testPriceIcon,
  closeModalIcon,
  successModalIcon,
  errorModalIcon,
  infoModalIcon,
  VariantIcon,
  StudentIcon,
  TestsIcon,
  VariantDeleteIcon,
  BtnArrowIcon,
  ComeBackIcon
}
